### ISSUE TITLE
Ideas and Suggestions

### ISSUE THREAD

**Issue by Jogai** [leonardoporro/Detached#3]
I'm happy I found this project as I am a user of graphdiff. How does it compare? Is the same featureset supported?

**Comment by leonardoporro** [comment]
Hi Jogai, thanks for writting...

As _graphdiff_, _detached_ supports persisting an entity graph that was deserialized or created on the fly.

Detached also provides events and plugins, so that, entities can be modified in the middle of the updating process. Some built-in plugins are Auditing (that automatically sets Created and Modified fields), Seeding, that allows to fill a DB with a json file, and there is also a kind of ManyToMany helper until EF Core team provides that feature. 

What is not  supported right now is changing the relationships on the fly by providing a configuration as GraphDiff does.
Detached's configuration is built on top of the (awesome) EF Core model metadata, and it is initialized with the DbContext, so it's difficult to change what is owned and what is associated once configured.

Detached might be faster that GraphDiff because I'm using EF Core's property accessors and avoding some DB access when adding associations, but I didn't benchmarked.

The project is new (about 2 months?) so it needs more work.
Any contribution and feature request is very welcome.

Best regards,
Leo

**Comment by Jogai** [comment]
Sounds awesome! Now that you mention it I see the plugins, I can use some of those too! "changing the relationships on the fly" is not something I use (I think...)

Hope to test it in the coming months, so you get probably some more feedback/requests by then 😃

**Comment by leonardoporro** [comment]
Thanks! It started with GraphDiff for EF core, but the idea is to write less code for tasks that we do over and over (DRY principle?).
There will be a ton of cases that won't fit with Detached and we will need to fall back to the original DbContext, but the simple CRUDs and some other cases would work out of the box.

**Comment by leonardoporro** [comment]
This is becoming something similar to a suite. I'll keep the components atomic and publish them in separate nugets.

**Comment by Jogai** [comment]
Since its renamed to Ideas and Suggestions and has a help wanted tag, here are some ideas:

- Global filtering 
- Batch update/delete 
- Future queries 
- Caching
- Auditing 

Inspired by https://github.com/jcachat/EntityFramework.DynamicFilters, https://github.com/loresoft/EntityFramework.Extended, http://entityframework-plus.net/, http://entityframework-extensions.net/

**Comment by leonardoporro** [comment]
Thanks a lot! 

Basic auditing is already implemented, but I need to update the documentation.
You need to enable the plugin, provide an ISessionInfo that contains the current user name and time, and add [CreatedBy], [ModifiedBy], [CreatedDate] and [ModifiedDate] attributes to the properties you want to get automatically updated (see unit test).
I think that implementing field-level audit is easy too, I have the break points where every field is updated.

I'll take a look after finishing with the demo and docs.
If you need any of those features asap, please add it as a separate issue.

**Comment by Jogai** [comment]
I don't need the features now, but those seem a common requirement and a nice fit for your project.

**Comment by stefan-stanca** [comment]
Sending a list of Ids (long) to DeleteAsync throws the following exception "Object must implement IConvertible."
Casting the list to an object array I get the following "One or more errors occurred. (Key values count mismatch, expected Id)"

**Comment by leonardoporro** [comment]
tracked as https://github.com/leonardoporro/Detached/issues/6
will fix this night

**Comment by leonardoporro** [comment]
Hi @stefan-stanca,
Originally, DeleteAsync took a list of objects as a parameter because I wanted to allow complex keys (primary keys with more than one column). It wasn't designed to delete multiple records.
I uploaded a new version that supports multiple delete by introducing a small object named KeyValue:

`await detachedContext.Set<Entity>().DeleteAsync(new KeyValue(1), new KeyValue(2));`

Hope it helps! Thanks for the feedback.
Please don't forget to Star if you like it.
